export const ALARM_SETTINGS = [
  {
    settingKey: 'temp-high',
    groupId: 'temperature',
    label: 'Temperature High Alarm',
    unit: '°C',
    min: -50.0,
    max: 150.0,
    step: 0.1,
    helperText: '-50.0 ~ 150.0 °C',
    initialFromDetail: (alarms) => alarms?.tempHigh ?? 0,
  },
  {
    settingKey: 'temp-low',
    groupId: 'temperature',
    label: 'Temperature Low Alarm',
    unit: '°C',
    min: -50.0,
    max: 150.0,
    step: 0.1,
    helperText: '-50.0 ~ 150.0 °C',
    initialFromDetail: (alarms) => alarms?.tempLow ?? 0,
  },
  {
    settingKey: 'volt-high',
    groupId: 'voltage',
    label: '24V High Alarm',
    unit: 'V',
    min: 0,
    max: 30.0,
    step: 0.1,
    helperText: '0 ~ 30.0 V',
    initialFromDetail: (alarms) => alarms?.voltHigh ?? 0,
  },
  {
    settingKey: 'volt-low',
    groupId: 'voltage',
    label: '24V Low Alarm',
    unit: 'V',
    min: 0,
    max: 30.0,
    step: 0.1,
    helperText: '0 ~ 30.0 V',
    initialFromDetail: (alarms) => alarms?.voltLow ?? 0,
  },
  {
    settingKey: 'ripple-high',
    groupId: 'ripple',
    label: 'Ripple High Alarm',
    unit: 'mV',
    min: 0,
    max: 1000,
    step: 1,
    helperText: '0 ~ 1000 mV',
    initialFromDetail: (alarms) => alarms?.rippleHigh ?? 0,
  },
  {
    settingKey: 'rf-out-high',
    groupId: 'rf-out',
    label: 'RF Output Total Power High Alarm',
    unit: 'dBmV',
    min: 0,
    max: 80.0,
    step: 0.1,
    helperText: '0 ~ 80.0 dBmV',
    // DTO field `rfOutputHigh` already exists from Stage 1.
    initialFromDetail: (alarms) => alarms?.rfOutputHigh ?? 0,
  },
  {
    settingKey: 'rf-out-low',
    groupId: 'rf-out',
    label: 'RF Output Total Power Low Alarm',
    unit: 'dBmV',
    min: 0,
    max: 80.0,
    step: 0.1,
    helperText: '0 ~ 80.0 dBmV',
    // rfOutputLow not in DTO yet; Commit 2b will add it.
    initialFromDetail: (alarms) => alarms?.rfOutputLow ?? 0,
  },
];

// Alarm Status Mask (paired with thresholds
export const ALARM_MASK_SETTINGS = [
  {
    settingKey: 'mask-temperature',
    groupId: 'temperature',
    label: 'Status Mask Temperature',
    initialFromDetail: (masks) => masks?.temperature ?? 0,
  },
  {
    settingKey: 'mask-volt-24v',
    groupId: 'voltage',
    label: 'Status Mask 24V',
    initialFromDetail: (masks) => masks?.volt24v ?? 0,
  },
  {
    settingKey: 'mask-volt-24v-ripple',
    groupId: 'ripple',
    label: 'Status Mask 24V Ripple',
    initialFromDetail: (masks) => masks?.volt24vRipple ?? 0,
  },
  {
    settingKey: 'mask-rf-out-total',
    groupId: 'rf-out',
    label: 'Status Mask RF Output Total Power',
    initialFromDetail: (masks) => masks?.rfOutTotal ?? 0,
  },
];

// Alarm Status Mask
export const ALARM_MASK_OTHER_SETTINGS = [
  {
    settingKey: 'mask-pilot-low-freq',
    label: 'Status Mask RF Output Pilot Low Frequency',
    initialFromDetail: (masks) => masks?.pilotLowFreq ?? 0,
  },
  {
    settingKey: 'mask-pilot-high-freq',
    label: 'Status Mask RF Output Pilot High Frequency',
    initialFromDetail: (masks) => masks?.pilotHighFreq ?? 0,
  },
  {
    settingKey: 'mask-tamp-switch',
    label: 'Status Mask Tamp Switch',
    initialFromDetail: (masks) => masks?.tampSwitch ?? 0,
  },
];

// RF Mode
export const RF_MODE_SETTINGS = [
  {
    settingKey: 'dfu-type',
    label: 'DFU type',
    widget: 'dropdown',
    options: [
      { value: 1, label: '1 — 204/258 MHz' },
      { value: 3, label: '3 — 396/492 MHz' },
      { value: 5, label: '5 — 684/834 MHz' },
      { value: 6, label: '6 — 85/105 MHz' },
    ],
    helperText: 'Setting DFU type (allowed: 1, 3, 5, 6)',
    initialFromDetail: (system) => system?.dfuType ?? 1,
  },
  {
    settingKey: 'alsc',
    label: 'ALSC (FWD AGC Mode)',
    widget: 'switch',
    options: [
      { value: 0, label: '0 — OFF (TGC mode)' },
      { value: 1, label: '1 — ON' },
    ],
    helperText: '0 — OFF (TGC mode), 1 — ON',
    initialFromDetail: (system) => system?.alsc ?? 0,
  },
  {
    settingKey: 'setting-mode',
    label: 'Setting Mode',
    widget: 'dropdown',
    options: [
      { value: 0, label: '0 — Bandwidth Pilot (Typical)' },
      { value: 1, label: '1 — User Setting Pilot' },
      { value: 3, label: '3 — Bench Test' },
    ],
    helperText: 'Pilot mode selection (allowed: 0, 1, 3)',
    initialFromDetail: (system) => system?.settingMode ?? 0,
  },
];

// RF Loading & Pilot
export const RF_LOADING_SETTINGS = [
  {
    settingKey: 'fwd-loading-low-freq',
    label: 'FWD Loading Low Freq',
    unit: 'MHz',
    min: 258,
    max: 1794,
    step: 1,
    helperText: '258 ~ 1794 MHz',
    initialFromDetail: (lp) => lp?.fwdLoadingLowFreq ?? 0,
  },
  {
    settingKey: 'fwd-loading-high-freq',
    label: 'FWD Loading High Freq',
    unit: 'MHz',
    min: 258,
    max: 1794,
    step: 1,
    helperText: '258 ~ 1794 MHz',
    initialFromDetail: (lp) => lp?.fwdLoadingHighFreq ?? 0,
  },
  {
    settingKey: 'fwd-loading-pwr-low',
    label: 'FWD Loading Pwr @ Low Freq',
    unit: 'dBmV',
    min: 20.0,
    max: 54.0,
    step: 0.1,
    helperText: '20.0 ~ 54.0 dBmV',
    initialFromDetail: (lp) => lp?.fwdLoadingPwrLow ?? 0,
  },
  {
    settingKey: 'fwd-loading-pwr-high',
    label: 'FWD Loading Pwr @ High Freq',
    unit: 'dBmV',
    min: 20.0,
    max: 54.0,
    step: 0.1,
    helperText: '20.0 ~ 54.0 dBmV',
    initialFromDetail: (lp) => lp?.fwdLoadingPwrHigh ?? 0,
  },
  {
    settingKey: 'fwd-pilot-low-freq',
    label: 'FWD Pilot Low Freq',
    unit: 'MHz',
    min: 261,
    max: 1791,
    step: 1,
    helperText: '261 ~ 1791 MHz',
    initialFromDetail: (lp) => lp?.fwdPilotLowFreq ?? 0,
  },
  {
    settingKey: 'fwd-pilot-high-freq',
    label: 'FWD Pilot High Freq',
    unit: 'MHz',
    min: 261,
    max: 1791,
    step: 1,
    helperText: '261 ~ 1791 MHz',
    initialFromDetail: (lp) => lp?.fwdPilotHighFreq ?? 0,
  },
];

// Bench Mode FWD
export const BENCH_FWD_SETTINGS = [
  {
    settingKey: 'fwd-input-pad-p1',
    label: 'Port 1 FWD Input PAD',
    unit: 'dB',
    min: 0,
    max: 20.0,
    step: 0.1,
    helperText: '0 ~ 20.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'fwd-input-eq-p1',
    label: 'Port 1 FWD Input EQ',
    unit: 'dB',
    min: 0,
    max: 12.0,
    step: 0.1,
    helperText: '0 ~ 12.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'fwd-output-pad-grp1',
    label: 'FWD Output PAD (group 1)',
    unit: 'dB',
    min: 0,
    max: 20.0,
    step: 0.1,
    helperText: '0 ~ 20.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'fwd-output-pad-grp2',
    label: 'FWD Output PAD (group 2)',
    unit: 'dB',
    min: 0,
    max: 20.0,
    step: 0.1,
    helperText: '0 ~ 20.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'fwd-output-eq-grp1',
    label: 'FWD Output EQ (group 1)',
    unit: 'dB',
    min: 0,
    max: 12.0,
    step: 0.1,
    helperText: '0 ~ 12.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'fwd-output-eq-grp2',
    label: 'FWD Output EQ (group 2)',
    unit: 'dB',
    min: 0,
    max: 12.0,
    step: 0.1,
    helperText: '0 ~ 12.0 dB',
    initialFromDetail: () => 0,
  },
];

// Bench Mode REV
export const BENCH_REV_SETTINGS = [
  {
    settingKey: 'rev-input-pad-grp1',
    label: 'REV Input PAD (group 1)',
    unit: 'dB',
    min: 0,
    max: 20.0,
    step: 0.1,
    helperText: '0 ~ 20.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'rev-input-pad-grp2',
    label: 'REV Input PAD (group 2)',
    unit: 'dB',
    min: 0,
    max: 20.0,
    step: 0.1,
    helperText: '0 ~ 20.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'rev-input-pad-grp3',
    label: 'REV Input PAD (group 3)',
    unit: 'dB',
    min: 0,
    max: 20.0,
    step: 0.1,
    helperText: '0 ~ 20.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'rev-output-eq-p1',
    label: 'Port 1 REV Output EQ',
    unit: 'dB',
    min: 0,
    max: 20.0,
    step: 0.1,
    helperText: '0 ~ 20.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'rev-output-pad-p1',
    label: 'Port 1 REV Output PAD',
    unit: 'dB',
    min: 0,
    max: 20.0,
    step: 0.1,
    helperText: '0 ~ 20.0 dB',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'rev-ingress-1',
    label: 'REV Ingress Setting #1',
    widget: 'dropdown',
    options: [
      { value: 0, label: '0 — 0dB (default)' },
      { value: 1, label: '1 — 3dB 30min' },
      { value: 2, label: '2 — 6dB 30min' },
      { value: 3, label: '3 — 12dB 30min' },
      { value: 4, label: '4 — Max dB 30min' },
    ],
    helperText: 'Bridge switch state',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'rev-ingress-2',
    label: 'REV Ingress Setting #2',
    widget: 'dropdown',
    options: [
      { value: 0, label: '0 — 0dB (default)' },
      { value: 1, label: '1 — 3dB 30min' },
      { value: 2, label: '2 — 6dB 30min' },
      { value: 3, label: '3 — 12dB 30min' },
      { value: 4, label: '4 — Max dB 30min' },
    ],
    helperText: 'Bridge switch state',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'rev-ingress-3',
    label: 'REV Ingress Setting #3',
    widget: 'dropdown',
    options: [
      { value: 0, label: '0 — 0dB (default)' },
      { value: 1, label: '1 — 3dB 30min' },
      { value: 2, label: '2 — 6dB 30min' },
      { value: 3, label: '3 — 12dB 30min' },
      { value: 4, label: '4 — Max dB 30min' },
    ],
    helperText: 'Bridge switch state',
    initialFromDetail: () => 0,
  },
];

// System Log
export const SYSTEM_LOG_SETTINGS = [
  {
    settingKey: 'sys-log-min',
    label: 'System Log Interval',
    widget: 'dropdown',
    options: [
      { value: 0,   label: '0 — Log OFF' },
      { value: 1,   label: '1 min' },
      { value: 2,   label: '2 min' },
      { value: 3,   label: '3 min' },
      { value: 5,   label: '5 min' },
      { value: 10,  label: '10 min' },
      { value: 15,  label: '15 min' },
      { value: 30,  label: '30 min (Typical)' },
      { value: 60,  label: '60 min' },
      { value: 120, label: '120 min' },
      { value: 180, label: '180 min' },
      { value: 240, label: '240 min' },
    ],
    helperText: 'Telemetry log cadence',
    initialFromDetail: (system) => system?.logIntervalMin ?? 30,
  },
  {
    settingKey: 'rf-output-log-min',
    label: 'RF Output Log Interval',
    widget: 'dropdown',
    options: [
      { value: 0,   label: '0 — Log OFF' },
      { value: 30,  label: '30 min (Typical)' },
      { value: 60,  label: '60 min' },
      { value: 120, label: '120 min' },
      { value: 180, label: '180 min' },
      { value: 240, label: '240 min' },
    ],
    helperText: 'RF output log cadence',
    initialFromDetail: () => 0,
  },
  {
    settingKey: 'fwd-eceq-index',
    label: 'FWD E-CEQ Index',
    unit: 'dB',
    min: 0,
    max: 24,
    step: 1,
    helperText: '0 ~ 24 dB',
    initialFromDetail: () => 0,
  },
];